### ISSUE TITLE
Feature request: Search and Raw scan results

### ISSUE THREAD

**Issue by seanmcfeely** [Aquarthur/urlscanio#11]
Hello, 

I'm looking to automate some work for my team and leverage the urlscan.io dataset. Your tool had almost all of the functions I needed except for an ability to search the urlscan.io dataset and also an easy way to get the raw scan results.

I will submit a PR shortly for an implementation I'm now using out-of-band. If you like it, let me know how to proceed. I would love to get this in your next pip version.

Thanks, 

Sean

**Comment by Aquarthur** [comment]
The PR you created for this functionality has been merged. I'll close the issue once a new version of `urlscanio` is pushed on PyPI.

**Comment by Aquarthur** [comment]
Took me a little while to get back to this, but I've pushed your changes to PyPI (urlscanio version 0.2.2). Thanks again for your contribution!
