### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by prabhumanis** [Aquarthur/urlscanio#21]
**OS : windows 10
python version: 3.10**

I have created a login in URLscanio and started using the URLscanio scan options.
I plan to automate my work via Python (https://pypi.org/project/urlscanio/#files-urlscanio 0.2.2).
So I downloaded the Python script module (urlscanio 0.2.2) and installed it on my machine. While running the script, I got the below error:  

C:\Users\sraj\AppData\Local\Programs\Python\Python310>urlscanio -i http://templatelab.com/
Traceback (most recent call last):
  File "C:\Users\sraj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sraj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\sraj\AppData\Local\Programs\Python\Python310\Scripts\urlscanio.exe\__main__.py", line 7, in <module>
  File "C:\Users\sraj\AppData\Local\Programs\Python\Python310\lib\site-packages\src\urlscanio\__main__.py", line 15, in main
    api_key = os.environ["URLSCAN_API_KEY"]
  File "C:\Users\sraj\AppData\Local\Programs\Python\Python310\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'URLSCAN_API_KEY'

**Where can I edit the script and add  my own URLSCAN_API_KEY ?
please help to resolve this error**

**Comment by briandoesdev** [comment]
You don't need to edit the script to add your API key. Instead you should create the _URLSCAN_API_KEY_ environment variable and set it to the value of your UrlScan.io API key.

Here is a quick step-by-step to do this for Windows:
1.  Login to your [urlscan.io](https://urlscan.io) account then navigate to [https://urlscan.io/user/profile/](https://urlscan.io/user/profile/). On the right hand side you'll see an "API Keys" section. 
2. Create a new key (name it whatever you want). 
3. After you create the key, create a new environment variable either by using `setx URLSCAN_API_KEY 'your-api-key'` or by using the Windows GUI via **Advanced Systems Settings**.
4. Close and re-open your terminal window.
5. Run the python script again

**Comment by Aquarthur** [comment]
Closing the issue as a solution was provided and no comment has been made in a few months.
